GS_INTRO = 1
GS_STARTING = 2
GS_PLAYING_NONSPECIFIC = 3  # general case for global state
GS_PLAYING_SHOW = 4
GS_PLAYING_TELL = 5
GS_PLAYING_FINISH = 6

GM_NORMAL = 1
GM_CHASE = 2
GM_MUSIC = 3
GAME_MODES = [GM_NORMAL, GM_CHASE, GM_MUSIC]  # used for cycling

BUTTON_SHOW_TIME = 1.0
BUTTON_IDLE_TIME = 0.5
